branches:
    only:
        - master

stages:
    - build

matrix:
    include:
        - language: java
          stage: build
          jdk: openjdk8
          install:
              - docker pull $DOCKER_AUX_REPO
              - sudo cp ci/protoc /bin/protoc
              - sudo chmod +x /bin/protoc
              - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
          script: mvn test -B

    sudo: true
    services:
        - docker
